### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by MathieuHaller** [SanoScience/FetalNet#1]
Hello,

Thank you for sharing your code !
I know this is a big thing to ask but I'm curious, do you have any plans to make your dataset public ?
Because this is honestly one of the biggest fetal datasets I've encountered in a paper, which makes the usage possibilities quite interesting.

**Comment by simongeek** [comment]
Hi @MathieuHaller!

Thank you for your interest in our research.

Unfortunately, we do not share the dataset right now.
If you would like to use the data, please use the pre-trained weights of our model.

Best regards,
Szymon

**Comment by Xadra-T** [comment]
Hi there,

When will you share the dataset?
